FROM ubuntu

WORKDIR /frontend

COPY . /frontend

RUN apt update && apt install curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -

RUN apt install build-essential


EXPOSE 5173
