version: "2"

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - "8080:8080"
    # volumes:
    #   - /volumes: /api
  ui:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

    # volumes:
    #   - /volumes: /api-ui

  # volumes:
  #   /volumes: /volumes
