version: "2"

services:
  api:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - /api_volume: /api
  ui:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - /api_volume-ui: /api-ui

  volumes:
    /volumes: /volumes
