FROM ubuntu

WORKDIR /api

COPY . /api


RUN apt-get update 

RUN apt-get install -y build-essential pip net-tools iputils-ping iproute2 curl

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -


RUN apt-get install -y nodejs

# RUN npm i mediasoup

RUN npm install

EXPOSE 8080

CMD ["npm","run","dev"]