FROM ubuntu

WORKDIR /api

COPY . /api


RUN apt-get update 

RUN apt-get install -y build-essential pip net-tools iputils-ping iproute2 curl

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -


RUN apt-get install -y nodejs

# RUN npm i mediasoup

RUN npm install

ENV URI=mongodb+srv://convo:2VfCdTQxFKQhzlsz@cluster0.kk7uwsh.mongodb.net/?retryWrites=true&w=majority \
    PORT=8080 \
    GOOGLE_CLIENT_ID=383953439865-8r0qsjorbce278b1g0vpnb036p9mhodo.apps.googleusercontent.com \
    GOOGLE_CLIENT_SECRET=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 \
    SessionSecret=d4a389be58cede97518f92398dba7e1eafaea6aac5d5f1111ce51728f388042e \
    UI=http://localhost:5173

EXPOSE 8080

CMD ["npm","run","dev"]